name: leeft
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  go_router: ^16.2.2
  json_annotation: ^4.9.0
  provider: ^6.1.5+1
  result_command: ^2.1.0
  result_dart: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/exercises.json
